# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RealPower', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ReactivePower', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Pf', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
