# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_switches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switches',
            name='Slider',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
