# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_auto_20170923_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switches',
            old_name='Buttons',
            new_name='Button',
        ),
    ]
