# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_auto_20170923_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shabeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shabeels', models.IntegerField()),
            ],
        ),
    ]
