# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_shabeel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shabeel',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='RealPower',
            new_name='ApparentPower',
        ),
        migrations.AddField(
            model_name='power',
            name='CurrentRMS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='TruePower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='VoltsRMS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
